# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe32f7bac8ba06841dd77a1e266698df51c8641e897eb4248475c658db433420a205e1b2daefabb77c9139ac01da5c29fb96bc0e1b68baa503210185a954d26

test:
  secret_key_base: badc2c59da55df93fad006298a7bf75c690636d957ca5cff4829df476c71333e318bfd9270ce91f3420c6fc2537ebbec9f66d53b86fac68b1ccf40750c3d7fba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
